In [1]:
import nltk
import numpy as np
import pandas as pd
import random
from sklearn.model_selection import train_test_split
import pprint, time

# Preprocessing of data

Here I will aim to form an array of arrays of tuples with each word and the following punctuation mark.

Example of single sentence:
[('I', ' '),
('love', ' '),
('kittens', ','),
('and', ' ').
('you', '?')]

In [2]:
from os import listdir
from os.path import isfile, join

datapath = 'target-sentences-tokenized'
onlyfiles = [join(datapath, f) for f in listdir(datapath) if isfile(join(datapath, f))]

In [3]:
data = []
punctuations = {',', '.', '!', '?'}
ignore = {'"', "'", '-', '–', '—', ':', ';'}
for file in onlyfiles:
    with open(file, 'r') as f:
        lines = f.readlines()
    for l in lines:
        words = l.split()
        curr_sent = []
        i = 0
        while i < len(words) - 1:
            current_pair = [words[i].lower()]
            if words[i].isnumeric():
                current_pair = ['NUM']
            if words[i] in ignore:
                i += 1
                continue
            if words[i + 1] in punctuations:
                current_pair.append(words[i + 1])
                i += 1
            elif words[i + 1] in ignore:
                current_pair.append(' ')
                i += 1
            else:
                current_pair.append(' ')
            curr_sent.append(tuple(current_pair))
            i += 1
        data.append(curr_sent)

In [4]:
data[:10]

[[('я', ' '),
  ('високий', ','),
  ('з', ' '),
  ('чорною', ' '),
  ('бородою', ' '),
  ('й', ' '),
  ('ненавиджу', ' '),
  ('публічність', '.')],
 [('я', ' '),
  ('не', ' '),
  ('маю', ' '),
  ('взагалі', ' '),
  ('грошей', ','),
  ('не', ' '),
  ('люблю', ' '),
  ('вівсянку', ','),
  ('а', ' '),
  ('єдине', ' '),
  ('прагнення', ' '),
  ('мого', ' '),
  ('життя', ' '),
  ('померти', ' '),
  ('в', ' '),
  ('достатку', '.')],
 [('ставлення', ' '),
  ('до', ' '),
  ('інших', ' '),
  ('холодне', ' '),
  ('й', ' '),
  ('безсердечне', '.')],
 [('я', ' '),
  ('не', ' '),
  ('піклуюсь', ' '),
  ('про', ' '),
  ('моїх', ' '),
  ('колег', ','),
  ('а', ' '),
  ('також', ' '),
  ('я', ' '),
  ('ще', ' '),
  ('не', ' '),
  ('дав', ' '),
  ('жодної', ' '),
  ('копійки', ' '),
  ('жебраку', ' '),
  ('чи', ' '),
  ('на', ' '),
  ('милостиню', '.')],
 [('що', ' '),
  ('ж', ','),
  ('мій', ' '),
  ('любий', ' '),
  ('лікарю', ','),
  ('се', ' '),
  ('справжній', ' '),
  ('опис', ' '),
  ('мене', ','

In [5]:
len(data)

29760

---------------

In [6]:
# split data into training and validation set in the ratio 90:10
train_set, test_set = train_test_split(data, train_size=0.9, test_size=0.009, random_state=101)

# create list of train and test tagged words
train_tagged_words = [tup for sent in train_set for tup in sent]
test_tagged_words = [tup for sent in test_set for tup in sent]
print(len(train_tagged_words))
print(len(test_tagged_words))

318802
3374


In [7]:
# check some tagged words.
train_tagged_words[:5]

[('усі', ' '),
 ('канали', ','),
 ('звичайно', ','),
 ('працюють', ' '),
 ('один', ' ')]

In [8]:
#use set datatype to check how many unique tags are present in training data
tags = {tag for word, tag in train_tagged_words}
print(len(tags))
print(tags)

# check total words in vocabulary
vocab = {word for word, tag in train_tagged_words}

5
{'.', '!', ' ', '?', ','}


In [9]:
# compute Emission Probability
def word_given_tag(word, tag, train_bag = train_tagged_words):
    tag_list = [pair for pair in train_bag if pair[1]==tag]
    count_tag = len(tag_list)#total number of times the passed tag occurred in train_bag
    w_given_tag_list = [pair[0] for pair in tag_list if pair[0]==word]
#now calculate the total number of times the passed word occurred as the passed tag.
    count_w_given_tag = len(w_given_tag_list)


    return (count_w_given_tag, count_tag)

# compute  Transition Probability
def t2_given_t1(t2, t1, train_bag=train_tagged_words):
    tags = [pair[1] for pair in train_bag]
    count_t1 = len([t for t in tags if t==t1])
    count_t2_t1 = 0
    for index in range(len(tags)-1):
        if tags[index]==t1 and tags[index+1] == t2:
            count_t2_t1 += 1
    return (count_t2_t1, count_t1)

# creating t x t transition matrix of tags, t= no of tags
# Matrix(i, j) represents P(jth tag after the ith tag)

tags_matrix = np.zeros((len(tags), len(tags)), dtype='float32')
for i, t1 in enumerate(list(tags)):
    for j, t2 in enumerate(list(tags)):
        tags_matrix[i, j] = t2_given_t1(t2, t1)[0]/t2_given_t1(t2, t1)[1]

print(tags_matrix)

[[0.03020698 0.01171781 0.85314316 0.00581088 0.09907314]
 [0.03418367 0.01479592 0.85510206 0.00255102 0.09336735]
 [0.07576954 0.00568155 0.7938994  0.00723846 0.11741104]
 [0.0250118  0.01179802 0.85983956 0.00707881 0.09627183]
 [0.01428732 0.0054628  0.8951143  0.00305356 0.08208203]]


In [10]:
# convert the matrix to a df for better readability
# the table is same as the transition table shown in section 3 of article
tags_df = pd.DataFrame(tags_matrix, columns=list(tags), index=list(tags))
display(tags_df)

.         !                   ?         ,
.  0.030207  0.011718  0.853143  0.005811  0.099073
!  0.034184  0.014796  0.855102  0.002551  0.093367
   0.075770  0.005682  0.793899  0.007238  0.117411
?  0.025012  0.011798  0.859840  0.007079  0.096272
,  0.014287  0.005463  0.895114  0.003054  0.082082

In [11]:
from tqdm import tqdm


def Viterbi(words, train_bag=train_tagged_words):
    state = []
    T = list(set([pair[1] for pair in train_bag]))

    for key, word in enumerate(tqdm(words)):
        # initialise list of probability column for a given observation
        p = []
        for tag in T:
            if key == 0:
                transition_p = tags_df.loc['.', tag] + tags_df.loc['?', tag] + tags_df.loc['!', tag]
            else:
                transition_p = tags_df.loc[state[-1], tag]

            # compute emission and state probabilities
            emission_p = word_given_tag(words[key], tag)[0]/word_given_tag(words[key], tag)[1]
            state_probability = emission_p * transition_p
            p.append(state_probability)

        pmax = max(p)
        # getting state for which probability is maximum
        state_max = T[p.index(pmax)]
        state.append(state_max)
    return list(zip(words, state))


In [12]:
# Let's test our Viterbi algorithm on a few sample sentences of test dataset
random.seed(1234)      #define a random seed to get same sentences when run multiple times

# choose random 10 numbers
rndom = [random.randint(1, len(test_set)) for x in range(10)]

# list of 10 sents on which we test the model
test_run = [test_set[i] for i in rndom]

# list of tagged words
test_run_base = [tup for sent in test_run for tup in sent]

# list of untagged words
test_tagged_words = [tup[0] for sent in test_run for tup in sent]

# Here We will only test 10 sentences to check the accuracy
# as testing the whole training set takes huge amount of time
start = time.time()
tagged_seq = Viterbi(test_tagged_words)
end = time.time()
difference = end-start

print("Time taken in seconds: ", difference)

# accuracy
check = [i for i, j in zip(tagged_seq, test_run_base) if i == j]

accuracy = len(check)/len(tagged_seq)
print('Viterbi Algorithm Accuracy: ', accuracy * 100)

100%|██████████| 116/116 [00:13<00:00,  8.59it/s]

Time taken in seconds:  13.537312030792236
Viterbi Algorithm Accuracy:  71.55172413793103


In [13]:
tagged_seq

[('звісно', ','),
 ('що', ' '),
 ('все', ' '),
 ('відбувалося', ' '),
 ('поступово', ' '),
 ('до', ' '),
 ('мого', ' '),
 ('першого', ' '),
 ('перерозгляду', '.'),
 ('(', ' '),
 ('після', ' '),
 ('складених', '.'),
 ('планів', ' '),
 (')', ' '),
 ('мало', ' '),
 ('пройти', ' '),
 ('з', ' '),
 ('пів', ' '),
 ('року', ' '),
 ('проте', ' '),
 ('все', ' '),
 ('відбулося', ' '),
 ('саме', ' '),
 ('так', ' '),
 ('як', ' '),
 ('планував', ' '),
 ('дух', ' '),
 ('торкнувся', ' '),
 ('його', ' '),
 ('до', ' '),
 ('руки', ' '),
 ('і', ' '),
 ('вказав', ' '),
 ('на', ' '),
 ('себе', ' '),
 ('молодшого', ' '),
 ('великий', ' '),
 ('ентузіазм', ' '),
 ('та', ' '),
 ('бажання', ' '),
 ('допомагати', ' '),
 ('бачив', ' '),
 ('дві', ' '),
 ('сувілі', '.'),
 ('але', ' '),
 ('замалі', '.'),
 ('бо', ' '),
 ('в', ' '),
 ('цьому', ' '),
 ('є', ' '),
 ('свій', ' '),
 ('специфічний', ' '),
 ('кайф', ' '),
 ('він', ' '),
 ('мимоволі', ' '),
 ('звернув', ' '),
 ('свій', ' '),
 ('погляд', ' '),
 ('туди', ' '),


In [ ]:
# Code to test all the test sentences
# (takes alot of time to run s0 we won't run it here)
# tagging the test sentences()
test_tagged_words = [tup for sent in test_set for tup in sent]
test_untagged_words = [tup[0] for sent in test_set for tup in sent]


print('Starting testing')
# start = time.time()
tagged_seq = Viterbi(test_untagged_words)
# end = time.time()
# difference = end-start

# print("Time taken in seconds: ", difference)


In [17]:
# accuracy
check = [i for i, j in zip(tagged_seq, test_untagged_words) if i == j]

accuracy = len(check) / len(tagged_seq)
print('Viterbi Algorithm Accuracy: ', accuracy * 100)

Viterbi Algorithm Accuracy:  0.0
